### PR TITLE
fix(cli): Use cross-spawn instead of kexec

### LINKED ISSUE #21: Windows support?
Hey @hemanth! I heard that this doesn't work on Windows. What needs to happen to get this to work on Windows?

### PR DESCRIPTION
**Pull request by kentcdodds**
Windows does not like kexec

Closes #21

### CODE REVIEW

**Comment by kentcdodds** [comment]
I tried it locally on my Mac and it works. Going to ask a windows user to try it.

**Comment by kentcdodds** [comment]
FYI, this is where I'm tracking progress for someone on windows: https://github.com/kentcdodds/es6-todomvc/issues/11

**Comment by hemanth** [comment]
So, any windows user gave a green on this?

**Comment by bhaveshgohel** [comment]
@hemanth @kentcdodds : Hello guys i have tried installing on Windows 7 64 bit.

Some of the issue:
- Its not the issue but on "process.platform" out put is "win32" and on [node.org](https://nodejs.org/download/nightly/v7.0.0-nightly201608074c86fa30d8/) it is "win" 
- The tar.gz file is not available for the current release [ i guess they will upload soon].

I am able to Finish the installation with some [modification](https://github.com/kentcdodds/node-nightly/compare/pr/fix-windows...bhaveshgohel:pr/fix-windows) need to test for my windows environment.

node-nightly

**Comment by kentcdodds** [comment]
Cool, that's helpful @bhaveshgohel.

I was really hoping to get this to work before my Webpack workshop that starts in a few hours. Unfortunately I don't have time to make that happen. But if someone else has a little bit of time that'd be amazing :)

**Comment by tarungarg546** [comment]
Done #23 .

**Comment by tarungarg546** [comment]
@hemanth should we close this ?

**Comment by hemanth** [comment]
Closing in favour of #23

**Pull request closed without merging**
